services:
  - type: web
    name: fastapi-telegram-bot
    env: python  # Specify the environment as Python
    plan: free   # You can start with Render's free plan
    buildCommand: pip install -r requirements.txt  # Install dependencies
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000  # Start FastAPI server
    autoDeploy: true  # Automatically deploy new commits pushed to the connected repo
